name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "**/requirements-dev.txt"
      - name: Semantic Release
        run: |
          pip install -r requirements-dev.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdir dist  
          semantic-release publish -v DEBUG
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
